# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arah.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1920, 1080)
        self.kanan = QtWidgets.QPushButton(Dialog)
        self.kanan.setGeometry(QtCore.QRect(400, 790, 101, 101))
        self.kanan.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border-right: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background-color: transparent; /* Latar belakang transparan */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(13, 47, 114, 0.4); /* Warna biru gelap dengan transparansi */\n"
"    color: #fffffe;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: rgba(169, 169, 169, 0.8); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff; /* Warna teks putih untuk kontras */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(170, 170, 170, 0.2); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.kanan.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("arrow-right (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kanan.setIcon(icon)
        self.kanan.setIconSize(QtCore.QSize(100, 100))
        self.kanan.setObjectName("kanan")
        self.kiri = QtWidgets.QPushButton(Dialog)
        self.kiri.setGeometry(QtCore.QRect(210, 790, 101, 101))
        self.kiri.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border-right: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background-color: transparent; /* Latar belakang transparan */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(13, 47, 114, 0.4); /* Warna biru gelap dengan transparansi */\n"
"    color: #fffffe;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: rgba(169, 169, 169, 0.8); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff; /* Warna teks putih untuk kontras */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(170, 170, 170, 0.2); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"")
        self.kiri.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("arrow-right (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kiri.setIcon(icon1)
        self.kiri.setIconSize(QtCore.QSize(100, 100))
        self.kiri.setObjectName("kiri")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(900, 850, 151, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lcdNumber = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber.setGeometry(QtCore.QRect(900, 700, 131, 71))
        self.lcdNumber.setObjectName("lcdNumber")
        self.kembali = QtWidgets.QPushButton(Dialog)
        self.kembali.setGeometry(QtCore.QRect(1770, 30, 101, 51))
        self.kembali.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border-right: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background-color: transparent; /* Latar belakang transparan */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(13, 47, 114, 0.4); /* Warna biru gelap dengan transparansi */\n"
"    color: #fffffe;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: rgba(169, 169, 169, 0.8); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff; /* Warna teks putih untuk kontras */\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(170, 170, 170, 0.2); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.kembali.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kembali.setIcon(icon2)
        self.kembali.setIconSize(QtCore.QSize(50, 50))
        self.kembali.setObjectName("kembali")
        self.gas = QtWidgets.QPushButton(Dialog)
        self.gas.setGeometry(QtCore.QRect(1690, 720, 71, 161))
        self.gas.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border-right: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background-color: transparent; /* Latar belakang transparan */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(13, 47, 114, 0.4); /* Warna biru gelap dengan transparansi */\n"
"    color: #fffffe;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: rgba(225, 244, 255, 0.3); /* Warna biru muda dengan transparansi */\n"
"    color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(170, 170, 170, 0.2); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.gas.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pedal gas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gas.setIcon(icon3)
        self.gas.setIconSize(QtCore.QSize(150, 150))
        self.gas.setObjectName("gas")
        self.rem = QtWidgets.QPushButton(Dialog)
        self.rem.setGeometry(QtCore.QRect(1590, 750, 71, 131))
        self.rem.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border-right: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background-color: transparent; /* Latar belakang transparan */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(13, 47, 114, 0.4); /* Warna biru gelap dengan transparansi */\n"
"    color: #fffffe;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: rgba(225, 244, 255, 0.3); /* Warna biru muda dengan transparansi */\n"
"    color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(170, 170, 170, 0.2); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.rem.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("pedal remm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rem.setIcon(icon4)
        self.rem.setIconSize(QtCore.QSize(120, 120))
        self.rem.setObjectName("rem")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(1920, 1080, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.kamera = QtWidgets.QLabel(Dialog)
        self.kamera.setGeometry(QtCore.QRect(10, 10, 1920, 1080))
        self.kamera.setObjectName("kamera")
        self.kamera.raise_()
        self.kanan.raise_()
        self.kiri.raise_()
        self.progressBar.raise_()
        self.lcdNumber.raise_()
        self.kembali.raise_()
        self.gas.raise_()
        self.rem.raise_()
        self.label.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.kamera.setText(_translate("Dialog", "CAMERA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
