# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1922, 1080)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("forest-fire-8681951_1920.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.exit = QtWidgets.QPushButton(Dialog)
        self.exit.setGeometry(QtCore.QRect(1450, 870, 81, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border-right: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background-color: transparent; /* Latar belakang transparan */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(13, 47, 114, 0.4); /* Warna biru gelap dengan transparansi */\n"
"    color: #fffffe;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: rgba(225, 244, 255, 0.3); /* Warna biru muda dengan transparansi */\n"
"    color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(170, 170, 170, 0.2); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.exit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("fire-exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit.setIcon(icon)
        self.exit.setIconSize(QtCore.QSize(68, 68))
        self.exit.setObjectName("exit")
        self.startt = QtWidgets.QPushButton(Dialog)
        self.startt.setGeometry(QtCore.QRect(1210, 870, 81, 61))
        self.startt.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border-right: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background-color: transparent; /* Latar belakang transparan */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(13, 47, 114, 0.4); /* Warna biru gelap dengan transparansi */\n"
"    color: #fffffe;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: rgba(225, 244, 255, 0.3); /* Warna biru muda dengan transparansi */\n"
"    color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(170, 170, 170, 0.2); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.startt.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("vehicle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startt.setIcon(icon1)
        self.startt.setIconSize(QtCore.QSize(60, 60))
        self.startt.setObjectName("startt")
        self.setting = QtWidgets.QPushButton(Dialog)
        self.setting.setGeometry(QtCore.QRect(1330, 870, 81, 61))
        self.setting.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    border-right: 1px solid #aaaaaa;\n"
"    border-bottom: 1px solid #aaaaaa;\n"
"    background-color: transparent; /* Latar belakang transparan */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgba(13, 47, 114, 0.4); /* Warna biru gelap dengan transparansi */\n"
"    color: #fffffe;\n"
"}\n"
"\n"
"QPushButton:hover:!pressed {\n"
"    background-color: rgba(225, 244, 255, 0.3); /* Warna biru muda dengan transparansi */\n"
"    color: #0c2f70;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgba(170, 170, 170, 0.2); /* Warna abu-abu dengan transparansi */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.setting.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("tools-and-utensils.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting.setIcon(icon2)
        self.setting.setIconSize(QtCore.QSize(50, 50))
        self.setting.setObjectName("setting")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(190, 150, 511, 121))
        font = QtGui.QFont()
        font.setFamily("FZShuTi")
        font.setPointSize(65)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setTabletTracking(False)
        self.label_3.setIndent(-3)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "PADAMIN"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
